name: iOS Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      lane:
        description: "beta or release"
        default: "beta"

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Fastlane
        run: gem install fastlane cocoapods --no-document

      - name: Restore API key
        run: |
          mkdir -p fastlane
          echo "${{ secrets.ASC_KEY_CONTENT }}" | base64 --decode > fastlane/AuthKey_4YK92UN5LD.p8

      - name: Deploy
        run: fastlane ${{ github.event.inputs.lane || 'beta' }}
